name: test github actions

on:
  # push:
  #   branches:
  #     "feature/**"
  pull_request:
    branches:
      "develop"



jobs:

  build-for-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo name
      run: |
        echo "::debug this activate"
        echo "::debug make PR and push the working branch"
        echo "::debug close PR and push the working branch again"
